bpy:
  context:
    scene:
      render:
        engine: # Blender internal engine for rendering
          # E.g. CYCLES, BLENDER_EEVEE, ...'
          CYCLES
          # BLENDER_EEVEE
        image_settings:
          color_mode: "RGBA" # ('RGB', 'RGBA', ...)
          file_format: "PNG" # ('PNG', 'OPEN_EXR', 'JPEG, ...)
        resolution_x: 137
        resolution_y: 137
scene_objects:
  cameras:
    - location: [1.0, 0.0, 0.0]
      max_depth_distance: 1.2
    # - location: [0, 1, 0.6]
    # - location: [8.0, 7.0, 4.0]

shapenet_root_path: "/media/pollenjp/DATAHDD8TB/share/share01/dataset/ShapeNet/ShapeNetCore.v1"
output_root_dir: "./output/rendering"
# metadata_filepath: ???
metadata_filepath: "/media/pollenjp/DATAHDD8TB/dataset/ShapeNet_for_P2M/ShapeNetP2M/04530566/ffffe224db39febe288b05b36358465d/rendering/rendering_metadata.txt"

debug_mode: true
debug: # if debug_mode is True
  output_dir: "output"
  blend_filepath: "${debug.output_dir}/debug.blend"
